version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: nour-postgres
    environment:
      POSTGRES_DB: nour
      POSTGRES_USER: nour
      POSTGRES_PASSWORD: nour
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nour -d nour"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: nour-backend
    environment:
      - DATABASE_URL=postgresql://nour:nour@postgres:5432/nour
      - JWT_SECRET=your-secret-key-change-in-production
      - LLM_ENABLED=false
      - UPLOAD_DIR=./uploads
    ports:
      - "8000:8000"
    volumes:
      - ../backend/uploads:/app/uploads
      - ../backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nour-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
